export const routes = {
  home: "/",
  products: "/products",
  productFamily: (slug: string) => `/products/${slug}` as const,
  product: (slug: string) => `/product/${slug}` as const,
  accessories: "/accessories",
  accessory: (slug: string) => `/accessories/${slug}` as const,
  spaces: "/spaces",
  space: (slug: string) => `/spaces/${slug}` as const,
  sectors: "/sectors",
  sector: (slug: string) => `/sectors/${slug}` as const,
  configure: "/configure",
  projects: "/projects",
  project: (slug: string) => `/projects/${slug}` as const,
  resources: "/resources",
  login: "/login",
  designSupport: "/design-support",
  partners: "/partners",
  partnerApply: "/partners/apply",
  partnerApplicationSuccess: "/partners/application-success",
  company: "/company",
  contact: "/contact",
  designSystem: "/design-system",
} as const;
