/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source?: string;
  destination?: string;
  permanent?: boolean;
  active?: boolean;
};

export type SeoDefaults = {
  _id: string;
  _type: "seoDefaults";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  defaults?: Seo;
  siteUrl?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  socialImage?: ImageWithAlt;
};

export type DesignSupportPage = {
  _id: string;
  _type: "designSupportPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  heroCopy?: PortableText;
  heroMedia?: Gallery;
  sections?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  seo?: Seo;
  audiences?: Array<string>;
  supportAreas?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
};

export type CompanyPage = {
  _id: string;
  _type: "companyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  heroCopy?: PortableText;
  heroMedia?: Gallery;
  sections?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  seo?: Seo;
  showParentBrandEndorsement?: boolean;
};

export type ProductFamilyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productFamily";
};

export type SpaceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "space";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eyebrow?: string;
  heroCopy?: PortableText;
  heroMedia?: Gallery;
  sections?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  seo?: Seo;
  featuredFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  featuredSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Gallery = {
  _type: "gallery";
  items?: Array<
    | ({
        _key: string;
      } & ImageWithAlt)
    | ({
        _key: string;
      } & Video)
  >;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        newWindow?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  brandLine?: string;
  items?: Array<{
    label?: string;
    href?: string;
    description?: string;
    children?: Array<
      {
        _key: string;
      } & Cta
    >;
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & Cta
  >;
  showEndorsement?: boolean;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  items?: Array<{
    label?: string;
    href?: string;
    description?: string;
    children?: Array<
      {
        _key: string;
      } & Cta
    >;
    _key: string;
  }>;
};

export type OfficeLocation = {
  _id: string;
  _type: "officeLocation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  address?: string;
  country?: string;
  region?: string;
  email?: string;
  phone?: string;
  mapUrl?: string;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  biography?: PortableText;
  portrait?: ImageWithAlt;
  email?: string;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type SectorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sector";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  body?: PortableText;
  heroImage?: ImageWithAlt;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  relatedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  relatedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  relatedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AccessoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "accessory";
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  resourceType?:
    | "product-brochure"
    | "product-data-sheet"
    | "technical-specification"
    | "cad"
    | "bim"
    | "revit"
    | "step"
    | "installation-guide"
    | "finish-card"
    | "sustainability-document"
    | "certification"
    | "planning-guide"
    | "video"
    | "product-image";
  productFamily?: ProductFamilyReference;
  product?: ProductReference;
  accessory?: AccessoryReference;
  sectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  file?: DownloadableFile;
  revisionHistory?: Array<{
    revision?: string;
    date?: string;
    notes?: string;
    _key: string;
  }>;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type DownloadableFile = {
  _type: "downloadableFile";
  title?: string;
  asset?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  format?: string;
  fileSize?: string;
  revision?: string;
  language?: string;
  accessLevel?: "public" | "registered" | "restricted";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName?: string;
  slug?: Slug;
  clientDisplayName?: string;
  location?: string;
  projectType?: string;
  sector?: SectorReference;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  challenge?: PortableText;
  approach?: PortableText;
  technologyRequirements?: Array<string>;
  productsUsed?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  accessoriesUsed?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  outcomes?: Array<string>;
  gallery?: Gallery;
  testimonial?: Quote;
  completionDate?: string;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type Quote = {
  _type: "quote";
  quote?: string;
  attribution?: string;
  role?: string;
  organisation?: string;
};

export type BrandSettings = {
  _id: string;
  _type: "brandSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  brandDescriptor?: string;
  brandLine?: string;
  shortDescription?: string;
  longDescription?: PortableText;
  logoLight?: ImageWithAlt;
  logoDark?: ImageWithAlt;
  brandSymbol?: ImageWithAlt;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColour?: string;
  accentColour?: string;
  showParentBrand?: boolean;
  hideParentBrand?: boolean;
  parentBrandName?: string;
  parentBrandLogo?: ImageWithAlt;
  relationshipText?: string;
  footerEndorsement?: boolean;
  companyPageEndorsement?: boolean;
  legalCompanyName?: string;
  contactDetails?: {
    email?: string;
    phone?: string;
    address?: string;
  };
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  region?: string;
  language?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SectorRelationship = {
  _type: "sectorRelationship";
  target?: SectorReference;
  relationship?: string;
  note?: string;
};

export type Sector = {
  _id: string;
  _type: "sector";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: PortableText;
  challenges?: Array<string>;
  typicalSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  heroMedia?: Gallery;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type SpaceRelationship = {
  _type: "spaceRelationship";
  target?: SpaceReference;
  relationship?: string;
  note?: string;
};

export type Space = {
  _id: string;
  _type: "space";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  group?: "Education" | "Corporate" | "Specialist" | "Public and Self-Service";
  description?: PortableText;
  primaryUsers?: Array<string>;
  activities?: Array<string>;
  designPriorities?: Array<string>;
  technologyRequirements?: Array<string>;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  recommendedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  relatedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  heroMedia?: Gallery;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type AccessoryRelationship = {
  _type: "accessoryRelationship";
  target?: AccessoryReference;
  relationship?: string;
  note?: string;
};

export type Accessory = {
  _id: string;
  _type: "accessory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  series?: string;
  model?: string;
  accessoryGroup?: string;
  descriptor?: string;
  description?: PortableText;
  heroMedia?: Gallery;
  specifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  compatibilityRules?: Array<
    {
      _key: string;
    } & CompatibilityRule
  >;
  compatibleProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  excludedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type ProductRelationship = {
  _type: "productRelationship";
  target?: ProductReference;
  relationship?: string;
  note?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  series?: string;
  model?: string;
  productFamily?: ProductFamilyReference;
  descriptor?: string;
  overview?: PortableText;
  heroMedia?: Gallery;
  gallery?: Gallery;
  featureStories?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  technicalSpecifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  finishes?: Array<
    {
      _key: string;
    } & FinishSwatch
  >;
  compatibleAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  configurable?: boolean;
  customisable?: boolean;
  enquiryOnly?: boolean;
  productStatus?: "placeholder" | "development" | "active" | "discontinued";
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type ProductFamily = {
  _id: string;
  _type: "productFamily";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortDescription?: string;
  longDescription?: PortableText;
  statement?: string;
  heroMedia?: Gallery;
  thumbnail?: ImageWithAlt;
  productTypes?: Array<string>;
  series?: Array<string>;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  keyCapabilities?: Array<string>;
  relatedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  status?: "draft" | "active" | "archived";
  publishAt?: string;
  seo?: Seo;
};

export type CompatibilityRule = {
  _type: "compatibilityRule";
  status?:
    "verified" | "provisional" | "requires-technical-review" | "not-compatible";
  notes?: string;
  installationType?: string;
  model?: string;
  requiredAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  excludedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
};

export type FinishSwatch = {
  _type: "finishSwatch";
  name?: string;
  code?: string;
  swatch?: ImageWithAlt;
  description?: string;
};

export type Metric = {
  _type: "metric";
  label?: string;
  value?: string;
  unit?: string;
  verified?: boolean;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
  style?: "primary" | "secondary" | "text";
};

export type FeatureStory = {
  _type: "featureStory";
  title?: string;
  description?: PortableText;
  media?: Gallery;
  technicalNote?: string;
};

export type SpecificationGroup = {
  _type: "specificationGroup";
  name?: string;
  items?: Array<
    {
      _key: string;
    } & SpecificationItem
  >;
};

export type SpecificationItem = {
  _type: "specificationItem";
  label?: string;
  value?: string;
  unit?: string;
  note?: string;
  verified?: boolean;
};

export type Video = {
  _type: "video";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  poster?: ImageWithAlt;
  title?: string;
  transcript?: string;
  autoplay?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Redirect
  | SeoDefaults
  | Seo
  | DesignSupportPage
  | CompanyPage
  | ProductFamilyReference
  | SpaceReference
  | ProjectReference
  | Homepage
  | Gallery
  | PortableText
  | Footer
  | Navigation
  | OfficeLocation
  | Person
  | SanityImageAssetReference
  | ImageWithAlt
  | PersonReference
  | ProductReference
  | SectorReference
  | Article
  | Slug
  | AccessoryReference
  | Resource
  | SanityFileAssetReference
  | DownloadableFile
  | Project
  | Quote
  | BrandSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SectorRelationship
  | Sector
  | SpaceRelationship
  | Space
  | AccessoryRelationship
  | Accessory
  | ProductRelationship
  | Product
  | ProductFamily
  | CompatibilityRule
  | FinishSwatch
  | Metric
  | Cta
  | FeatureStory
  | SpecificationGroup
  | SpecificationItem
  | Video
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/cms/queries.ts
// Variable: PRODUCT_FAMILIES_QUERY
// Query: *[_type == "productFamily" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": shortDescription}
export type PRODUCT_FAMILIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "productFamily";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  shortDescription?: string;
  longDescription?: PortableText;
  statement?: string;
  heroMedia?: Gallery;
  thumbnail?: ImageWithAlt;
  productTypes?: Array<string>;
  series?: Array<string>;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  keyCapabilities?: Array<string>;
  relatedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | null;
}>;

// Source: src/lib/cms/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Product details"), "productFamily": productFamily->_id}
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  series?: string;
  model?: string;
  productFamily: string | null;
  descriptor?: string;
  overview?: PortableText;
  heroMedia?: Gallery;
  gallery?: Gallery;
  featureStories?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  technicalSpecifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  finishes?: Array<
    {
      _key: string;
    } & FinishSwatch
  >;
  compatibleAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  configurable?: boolean;
  customisable?: boolean;
  enquiryOnly?: boolean;
  productStatus?: "active" | "development" | "discontinued" | "placeholder";
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | "Product details";
}>;

// Source: src/lib/cms/queries.ts
// Variable: ACCESSORIES_QUERY
// Query: *[_type == "accessory" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Accessory details")}
export type ACCESSORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "accessory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  series?: string;
  model?: string;
  accessoryGroup?: string;
  descriptor?: string;
  description?: PortableText;
  heroMedia?: Gallery;
  specifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  compatibilityRules?: Array<
    {
      _key: string;
    } & CompatibilityRule
  >;
  compatibleProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  excludedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | "Accessory details";
}>;

// Source: src/lib/cms/queries.ts
// Variable: SPACES_QUERY
// Query: *[_type == "space" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Space details")}
export type SPACES_QUERY_RESULT = Array<{
  _id: string;
  _type: "space";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  group?: "Corporate" | "Education" | "Public and Self-Service" | "Specialist";
  description?: PortableText;
  primaryUsers?: Array<string>;
  activities?: Array<string>;
  designPriorities?: Array<string>;
  technologyRequirements?: Array<string>;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  recommendedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  relatedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  heroMedia?: Gallery;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
}>;

// Source: src/lib/cms/queries.ts
// Variable: SECTORS_QUERY
// Query: *[_type == "sector" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Sector details")}
export type SECTORS_QUERY_RESULT = Array<{
  _id: string;
  _type: "sector";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  description?: PortableText;
  challenges?: Array<string>;
  typicalSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  heroMedia?: Gallery;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
}>;

// Source: src/lib/cms/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && status == "active"] | order(completionDate desc){..., "slug": slug.current, "title": projectName, "summary": coalesce(pt::text(approach), pt::text(challenge), "Project details")}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName?: string;
  slug: string | null;
  clientDisplayName?: string;
  location?: string;
  projectType?: string;
  sector?: SectorReference;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  challenge?: PortableText;
  approach?: PortableText;
  technologyRequirements?: Array<string>;
  productsUsed?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  accessoriesUsed?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  outcomes?: Array<string>;
  gallery?: Gallery;
  testimonial?: Quote;
  completionDate?: string;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
}>;

// Source: src/lib/cms/queries.ts
// Variable: RESOURCES_QUERY
// Query: *[_type == "resource" && status == "active"] | order(_updatedAt desc){..., "slug": slug.current, "summary": coalesce(file.title, "Resource details")}
export type RESOURCES_QUERY_RESULT = Array<{
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: string | null;
  resourceType?:
    | "bim"
    | "cad"
    | "certification"
    | "finish-card"
    | "installation-guide"
    | "planning-guide"
    | "product-brochure"
    | "product-data-sheet"
    | "product-image"
    | "revit"
    | "step"
    | "sustainability-document"
    | "technical-specification"
    | "video";
  productFamily?: ProductFamilyReference;
  product?: ProductReference;
  accessory?: AccessoryReference;
  sectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  file?: DownloadableFile;
  revisionHistory?: Array<{
    revision?: string;
    date?: string;
    notes?: string;
    _key: string;
  }>;
  status: "active";
  publishAt?: string;
  seo?: Seo;
  summary: string | "Resource details";
}>;

// Source: src/lib/cms/queries.ts
// Variable: PRODUCT_FAMILY_QUERY
// Query: *[_type == "productFamily" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": shortDescription}
export type PRODUCT_FAMILY_QUERY_RESULT = {
  _id: string;
  _type: "productFamily";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  shortDescription?: string;
  longDescription?: PortableText;
  statement?: string;
  heroMedia?: Gallery;
  thumbnail?: ImageWithAlt;
  productTypes?: Array<string>;
  series?: Array<string>;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  keyCapabilities?: Array<string>;
  relatedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | null;
} | null;

// Source: src/lib/cms/queries.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Product details"), "productFamily": productFamily->_id}
export type PRODUCT_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  series?: string;
  model?: string;
  productFamily: string | null;
  descriptor?: string;
  overview?: PortableText;
  heroMedia?: Gallery;
  gallery?: Gallery;
  featureStories?: Array<
    {
      _key: string;
    } & FeatureStory
  >;
  technicalSpecifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  finishes?: Array<
    {
      _key: string;
    } & FinishSwatch
  >;
  compatibleAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  supportedSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  supportedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  configurable?: boolean;
  customisable?: boolean;
  enquiryOnly?: boolean;
  productStatus?: "active" | "development" | "discontinued" | "placeholder";
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | "Product details";
} | null;

// Source: src/lib/cms/queries.ts
// Variable: ACCESSORY_QUERY
// Query: *[_type == "accessory" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Accessory details")}
export type ACCESSORY_QUERY_RESULT = {
  _id: string;
  _type: "accessory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  series?: string;
  model?: string;
  accessoryGroup?: string;
  descriptor?: string;
  description?: PortableText;
  heroMedia?: Gallery;
  specifications?: Array<
    {
      _key: string;
    } & SpecificationGroup
  >;
  compatibilityRules?: Array<
    {
      _key: string;
    } & CompatibilityRule
  >;
  compatibleProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  requiredAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  excludedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  downloads?: Array<
    {
      _key: string;
    } & DownloadableFile
  >;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string | "Accessory details";
} | null;

// Source: src/lib/cms/queries.ts
// Variable: SPACE_QUERY
// Query: *[_type == "space" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Space details")}
export type SPACE_QUERY_RESULT = {
  _id: string;
  _type: "space";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  group?: "Corporate" | "Education" | "Public and Self-Service" | "Specialist";
  description?: PortableText;
  primaryUsers?: Array<string>;
  activities?: Array<string>;
  designPriorities?: Array<string>;
  technologyRequirements?: Array<string>;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  recommendedAccessories?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  relatedSectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  heroMedia?: Gallery;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
} | null;

// Source: src/lib/cms/queries.ts
// Variable: SECTOR_QUERY
// Query: *[_type == "sector" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Sector details")}
export type SECTOR_QUERY_RESULT = {
  _id: string;
  _type: "sector";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug: string | null;
  description?: PortableText;
  challenges?: Array<string>;
  typicalSpaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  recommendedFamilies?: Array<
    {
      _key: string;
    } & ProductFamilyReference
  >;
  recommendedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  heroMedia?: Gallery;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
} | null;

// Source: src/lib/cms/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{..., "slug": slug.current, "title": projectName, "summary": coalesce(pt::text(approach), pt::text(challenge), "Project details")}
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName?: string;
  slug: string | null;
  clientDisplayName?: string;
  location?: string;
  projectType?: string;
  sector?: SectorReference;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  challenge?: PortableText;
  approach?: PortableText;
  technologyRequirements?: Array<string>;
  productsUsed?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  accessoriesUsed?: Array<
    {
      _key: string;
    } & AccessoryReference
  >;
  outcomes?: Array<string>;
  gallery?: Gallery;
  testimonial?: Quote;
  completionDate?: string;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  title: string | null;
  summary: string;
} | null;

// Source: src/lib/cms/queries.ts
// Variable: RESOURCE_QUERY
// Query: *[_type == "resource" && slug.current == $slug][0]{..., "slug": slug.current, "summary": coalesce(file.title, "Resource details")}
export type RESOURCE_QUERY_RESULT = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: string | null;
  resourceType?:
    | "bim"
    | "cad"
    | "certification"
    | "finish-card"
    | "installation-guide"
    | "planning-guide"
    | "product-brochure"
    | "product-data-sheet"
    | "product-image"
    | "revit"
    | "step"
    | "sustainability-document"
    | "technical-specification"
    | "video";
  productFamily?: ProductFamilyReference;
  product?: ProductReference;
  accessory?: AccessoryReference;
  sectors?: Array<
    {
      _key: string;
    } & SectorReference
  >;
  spaces?: Array<
    {
      _key: string;
    } & SpaceReference
  >;
  file?: DownloadableFile;
  revisionHistory?: Array<{
    revision?: string;
    date?: string;
    notes?: string;
    _key: string;
  }>;
  status?: "active" | "archived" | "draft";
  publishAt?: string;
  seo?: Seo;
  summary: string | "Resource details";
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "productFamily" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": shortDescription}': PRODUCT_FAMILIES_QUERY_RESULT;
    '*[_type == "product" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Product details"), "productFamily": productFamily->_id}': PRODUCTS_QUERY_RESULT;
    '*[_type == "accessory" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Accessory details")}': ACCESSORIES_QUERY_RESULT;
    '*[_type == "space" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Space details")}': SPACES_QUERY_RESULT;
    '*[_type == "sector" && status == "active"] | order(name asc){..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Sector details")}': SECTORS_QUERY_RESULT;
    '*[_type == "project" && status == "active"] | order(completionDate desc){..., "slug": slug.current, "title": projectName, "summary": coalesce(pt::text(approach), pt::text(challenge), "Project details")}': PROJECTS_QUERY_RESULT;
    '*[_type == "resource" && status == "active"] | order(_updatedAt desc){..., "slug": slug.current, "summary": coalesce(file.title, "Resource details")}': RESOURCES_QUERY_RESULT;
    '*[_type == "productFamily" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": shortDescription}': PRODUCT_FAMILY_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Product details"), "productFamily": productFamily->_id}': PRODUCT_QUERY_RESULT;
    '*[_type == "accessory" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(descriptor, "Accessory details")}': ACCESSORY_QUERY_RESULT;
    '*[_type == "space" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Space details")}': SPACE_QUERY_RESULT;
    '*[_type == "sector" && slug.current == $slug][0]{..., "slug": slug.current, "title": name, "summary": coalesce(pt::text(description), "Sector details")}': SECTOR_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{..., "slug": slug.current, "title": projectName, "summary": coalesce(pt::text(approach), pt::text(challenge), "Project details")}': PROJECT_QUERY_RESULT;
    '*[_type == "resource" && slug.current == $slug][0]{..., "slug": slug.current, "summary": coalesce(file.title, "Resource details")}': RESOURCE_QUERY_RESULT;
  }
}
