import type {
  AspectRatioName,
  ImageFormat,
  MediaAsset,
  MediaCategory,
  ModelFormat,
  VideoFormat,
} from "@/types/media";

export const aspectRatios: Record<
  AspectRatioName,
  { width: number; height: number; ratio: number }
> = {
  "homepage-hero": { width: 16, height: 9, ratio: 16 / 9 },
  "product-family-hero": { width: 16, height: 9, ratio: 16 / 9 },
  "product-hero": { width: 4, height: 3, ratio: 4 / 3 },
  "product-tile": { width: 4, height: 3, ratio: 4 / 3 },
  "editorial-feature": { width: 3, height: 2, ratio: 3 / 2 },
  "portrait-story": { width: 4, height: 5, ratio: 4 / 5 },
  "finish-swatch": { width: 1, height: 1, ratio: 1 },
  "mobile-hero": { width: 4, height: 5, ratio: 4 / 5 },
};
export const mediaCategories: MediaCategory[] = [
  "product-cutout",
  "product-hero",
  "product-detail",
  "product-environment",
  "product-family-hero",
  "space-hero",
  "sector-hero",
  "project-media",
  "finish-swatch",
  "technical-diagram",
  "video",
  "360-sequence",
  "3d-poster",
];
export const supportedMediaFormats: {
  images: ImageFormat[];
  video: VideoFormat[];
  models: ModelFormat[];
} = {
  images: ["png", "jpg", "jpeg", "webp", "avif"],
  video: ["mp4", "webm"],
  models: ["glb", "usdz"],
};
const blur =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSIzMCI+PHJlY3Qgd2lkdGg9IjQwIiBoZWlnaHQ9IjMwIiBmaWxsPSIjZTVlNWUxIi8+PC9zdmc+";

function accessoryConcept(id: string, slug: string, alt: string): MediaAsset {
  return {
    id,
    category: "product-detail",
    kind: "image",
    src: `/media/accessories/${slug}-concept.png`,
    alt,
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative accessory concept — final design and compatibility are not verified.",
    credit: "TEVORA concept visualisation",
  };
}

export const mediaAssets = {
  homepageHero: {
    id: "homepage-learning-hero",
    category: "space-hero",
    kind: "image",
    src: "/media/home/technology-learning-hero.png",
    alt: "Technology-enabled university collaboration space with an integrated presentation station, display and flexible learning furniture",
    width: 1672,
    height: 941,
    aspectRatio: "homepage-hero",
    focalPoint: { x: 0.62, y: 0.5 },
    mobileFocalPoint: { x: 0.66, y: 0.5 },
    blurDataURL: blur,
    caption: "Representative technology-enabled learning environment.",
    credit: "TEVORA",
  },
  mobileAvStory: {
    id: "mobile-av-cart-story",
    category: "product-environment",
    kind: "image",
    src: "/media/home/mobile-av-cart-story.png",
    alt: "Graphite mobile AV cart with integrated display, camera and soundbar in a flexible teaching space",
    width: 1448,
    height: 1086,
    aspectRatio: "product-hero",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption: "Representative mobile AV furniture application.",
    credit: "TEVORA",
  },
  arcConcept: {
    id: "arc-presentation-station-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/presentation-stations/arc-concept.png",
    alt: "Concept render of a compact graphite and light-oak ARC presentation station",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  arcProConcept: {
    id: "arc-pro-presentation-station-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/presentation-stations/arc-pro-concept.png",
    alt: "Concept render of a wide graphite and light-oak ARC Pro multimedia presentation station",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  liftAccessConcept: {
    id: "lift-access-presentation-station-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/presentation-stations/lift-access-concept.png",
    alt: "Concept render of an open height-adjustable graphite and light-oak LIFT Access presentation station",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  eduStationConcept: {
    id: "edu-instructor-station-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/presentation-stations/edu-station-concept.png",
    alt: "Concept render of a graphite and light-oak EDU multimedia instructor station",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  eduTeachingDeskConcept: {
    id: "edu-teaching-desk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/learning-furniture/edu-teaching-desk-concept.png",
    alt: "Concept render of a graphite and light-oak EDU technology-ready teaching desk",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  learnCollaborationTableConcept: {
    id: "learn-collaboration-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/learning-furniture/learn-collaboration-table-concept.png",
    alt: "Concept render of a four-person graphite and light-oak LEARN collaboration table",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  labTechnologyBenchConcept: {
    id: "lab-technology-bench-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/learning-furniture/lab-technology-bench-concept.png",
    alt: "Concept render of a graphite and light-oak LAB technology teaching bench",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  flexMobileConcept: {
    id: "flex-mobile-learning-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/learning-furniture/flex-mobile-concept.png",
    alt: "Concept render of two mobile graphite and light-oak FLEX learning tables",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  moveCartConcept: {
    id: "move-mobile-av-cart-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/mobile-av-carts/move-mobile-av-cart-concept.png",
    alt: "Concept render of a compact graphite MOVE single-display mobile AV cart with an oak device shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  moveProCartConcept: {
    id: "move-pro-mobile-av-cart-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/mobile-av-carts/move-pro-mobile-av-cart-concept.png",
    alt: "Concept render of a graphite MOVE Pro video-collaboration cart with an oak shelf and ventilated equipment enclosure",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  moveDuoCartConcept: {
    id: "move-duo-mobile-av-cart-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/mobile-av-carts/move-duo-mobile-av-cart-concept.png",
    alt: "Concept render of a wide graphite MOVE Duo dual-display mobile AV cart with an oak equipment shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  moveEduCartConcept: {
    id: "move-edu-mobile-av-cart-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/mobile-av-carts/move-edu-mobile-av-cart-concept.png",
    alt: "Concept render of a graphite MOVE Edu interactive-display cart with an oak teaching shelf and equipment enclosure",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  moveXlCartConcept: {
    id: "move-xl-mobile-av-cart-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/mobile-av-carts/move-xl-mobile-av-cart-concept.png",
    alt: "Concept render of a large-format graphite MOVE XL mobile AV cart with an oak shelf and ventilated equipment enclosure",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  nexusCredenzaConcept: {
    id: "nexus-technology-credenza-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technology-credenzas/nexus-technology-credenza-concept.png",
    alt: "Concept render of a long graphite and light-oak NEXUS technology credenza with four equipment bays",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  nexusCompactCredenzaConcept: {
    id: "nexus-compact-credenza-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technology-credenzas/nexus-compact-credenza-concept.png",
    alt: "Concept render of a compact graphite and light-oak NEXUS Compact technology credenza",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  nexusRackCredenzaConcept: {
    id: "nexus-rack-credenza-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technology-credenzas/nexus-rack-credenza-concept.png",
    alt: "Concept render of a graphite and light-oak NEXUS Rack credenza with one open empty equipment bay",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  nexusEduCredenzaConcept: {
    id: "nexus-edu-credenza-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technology-credenzas/nexus-edu-credenza-concept.png",
    alt: "Concept render of a graphite and light-oak NEXUS Edu classroom technology credenza",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  nexusWallCredenzaConcept: {
    id: "nexus-wall-credenza-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technology-credenzas/nexus-wall-credenza-concept.png",
    alt: "Concept render of a wall-mounted graphite and light-oak NEXUS Wall technology credenza",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  coreEnclosureConcept: {
    id: "core-equipment-enclosure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/av-equipment-enclosures/core-equipment-enclosure-concept.png",
    alt: "Concept render of a closed graphite CORE AV equipment enclosure with perforated service doors and light-oak accents",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  coreCompactEnclosureConcept: {
    id: "core-compact-enclosure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/av-equipment-enclosures/core-compact-enclosure-concept.png",
    alt: "Concept render of a compact graphite CORE Compact equipment enclosure with a light-oak top insert",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  coreWallEnclosureConcept: {
    id: "core-wall-enclosure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/av-equipment-enclosures/core-wall-enclosure-concept.png",
    alt: "Concept render of a wall-mounted graphite CORE Wall equipment enclosure with a perforated service door",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  coreMobileEnclosureConcept: {
    id: "core-mobile-enclosure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/av-equipment-enclosures/core-mobile-enclosure-concept.png",
    alt: "Concept render of a mobile graphite CORE Mobile equipment enclosure with light-oak accents and four casters",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  coreRackEnclosureConcept: {
    id: "core-rack-enclosure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/av-equipment-enclosures/core-rack-enclosure-concept.png",
    alt: "Concept render of a tall graphite CORE Rack enclosure with an open perforated door and empty internal mounting frame",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  panelControllerStandConcept: {
    id: "panel-controller-stand-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/room-control-scheduling/panel-controller-stand-concept.png",
    alt: "Concept render of a freestanding graphite PANEL touch-controller stand with a light-oak interface surround",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  panelDeskControllerConcept: {
    id: "panel-desk-controller-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/room-control-scheduling/panel-desk-controller-concept.png",
    alt: "Concept render of a graphite and light-oak PANEL Desk touch-controller housing mounted through a tabletop sample",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  panelWallControllerConcept: {
    id: "panel-wall-controller-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/room-control-scheduling/panel-wall-controller-concept.png",
    alt: "Concept render of a wall-mounted graphite PANEL Wall touch-controller enclosure with a light-oak accent",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  scheduleRoomPanelConcept: {
    id: "schedule-room-panel-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/room-control-scheduling/schedule-room-panel-concept.png",
    alt: "Concept render of a slim graphite SCHEDULE room-panel enclosure beside a light-oak architectural slat panel",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  dockTabletConcept: {
    id: "dock-tablet-dock-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/room-control-scheduling/dock-tablet-dock-concept.png",
    alt: "Concept render of a portrait tablet placeholder in a graphite and light-oak DOCK tabletop enclosure",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  mediawallConcept: {
    id: "mediawall-display-wall-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/media-walls-space-dividers/mediawall-display-wall-concept.png",
    alt: "Concept render of a fixed graphite and light-oak MEDIAWALL display-integrated wall",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  mediawallMobileConcept: {
    id: "mediawall-mobile-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/media-walls-space-dividers/mediawall-mobile-concept.png",
    alt: "Concept render of a mobile graphite and light-oak MEDIAWALL with integrated display position and low-profile casters",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  boundaryDividerConcept: {
    id: "boundary-space-divider-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/media-walls-space-dividers/boundary-space-divider-concept.png",
    alt: "Concept render of three connected graphite, muted green and light-oak BOUNDARY space-divider modules",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  shiftPartitionConcept: {
    id: "shift-mobile-partition-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/media-walls-space-dividers/shift-mobile-partition-concept.png",
    alt: "Concept render of two mobile graphite, muted green and light-oak SHIFT partition modules",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  focusCollaborationWallConcept: {
    id: "focus-collaboration-wall-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/media-walls-space-dividers/focus-collaboration-wall-concept.png",
    alt: "Concept render of a graphite FOCUS display-integrated collaboration wall with angled muted-green side panels",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  vistaDisplayStandConcept: {
    id: "vista-single-display-stand-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/display-stands/vista-single-display-stand-concept.png",
    alt: "Concept render of a fixed graphite VISTA single-display stand with an oak equipment shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  vistaDuoDisplayStandConcept: {
    id: "vista-duo-display-stand-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/display-stands/vista-duo-display-stand-concept.png",
    alt: "Concept render of a wide graphite VISTA Duo dual-display stand with an oak equipment shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  vistaXlDisplayStandConcept: {
    id: "vista-xl-display-stand-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/display-stands/vista-xl-display-stand-concept.png",
    alt: "Concept render of a large-format graphite VISTA XL display stand with a ventilated oak equipment enclosure",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  frameDisplayStructureConcept: {
    id: "frame-floor-to-wall-display-structure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/display-stands/frame-floor-to-wall-concept.png",
    alt: "Concept render of a full-height graphite FRAME display structure with an oak device shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  frameWallDisplayStructureConcept: {
    id: "frame-wall-display-structure-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/display-stands/frame-wall-concept.png",
    alt: "Concept render of a wall-mounted graphite FRAME Wall display structure with an oak device shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  forumTableConcept: {
    id: "forum-boardroom-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/collaboration-tables/forum-boardroom-table-concept.png",
    alt: "Concept render of a long graphite and light-oak FORUM technology-integrated boardroom table",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  convergeTableConcept: {
    id: "converge-video-conference-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/collaboration-tables/converge-video-conference-table-concept.png",
    alt: "Concept render of a tapered graphite and light-oak CONVERGE video-conference table",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  huddleTableConcept: {
    id: "huddle-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/collaboration-tables/huddle-table-concept.png",
    alt: "Concept render of a compact graphite and light-oak HUDDLE technology-ready table",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  linkModularTableConcept: {
    id: "link-modular-table-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/collaboration-tables/link-modular-table-concept.png",
    alt: "Concept render of three connected graphite and light-oak LINK Modular collaboration-table modules",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  touchKioskConcept: {
    id: "touch-floor-kiosk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/interactive-kiosks/touch-floor-kiosk-concept.png",
    alt: "Concept render of a floor-standing graphite TOUCH interactive kiosk with a light-oak screen surround",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  touchWallKioskConcept: {
    id: "touch-wall-kiosk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/interactive-kiosks/touch-wall-kiosk-concept.png",
    alt: "Concept render of a wall-mounted graphite TOUCH Wall kiosk with a light-oak screen surround",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  touchMiniKioskConcept: {
    id: "touch-mini-kiosk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/interactive-kiosks/touch-mini-kiosk-concept.png",
    alt: "Concept render of a compact graphite TOUCH Mini tablet kiosk with a light-oak surround",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  wayKioskConcept: {
    id: "way-wayfinding-kiosk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/interactive-kiosks/way-wayfinding-kiosk-concept.png",
    alt: "Concept render of a tall graphite WAY wayfinding kiosk with a light-oak side blade",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  checkKioskConcept: {
    id: "check-registration-kiosk-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/interactive-kiosks/check-registration-kiosk-concept.png",
    alt: "Concept render of a graphite CHECK visitor-registration kiosk with an angled blank interface and light-oak shelf",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  analystWorkstationConcept: {
    id: "analyst-technical-workstation-concept",
    category: "product-detail",
    kind: "image",
    src: "/media/products/technical-workstations/analyst-workstation-concept.png",
    alt: "Representative concept render of a graphite and light-oak ANALYST technical workstation with three display-support arms",
    width: 1448,
    height: 1086,
    aspectRatio: "product-tile",
    focalPoint: { x: 0.5, y: 0.5 },
    blurDataURL: blur,
    caption:
      "Representative concept imagery — final product design and details are not verified.",
    credit: "TEVORA concept visualisation",
  },
  displayMountingAccessoryConcept: accessoryConcept(
    "display-mounting-accessory-concept",
    "display-mounting",
    "Representative graphite display-mounting accessory kit with rails and adjustable arms",
  ),
  cameraMountingAccessoryConcept: accessoryConcept(
    "camera-mounting-accessory-concept",
    "camera-mounting",
    "Representative graphite camera-mounting accessory kit with rail and adjustable shelves",
  ),
  soundbarMountingAccessoryConcept: accessoryConcept(
    "soundbar-mounting-accessory-concept",
    "soundbar-mounting",
    "Representative graphite soundbar-mounting accessory kit with adjustable brackets",
  ),
  deviceShelvesAccessoryConcept: accessoryConcept(
    "device-shelves-accessory-concept",
    "device-shelves",
    "Representative family of graphite device shelves with ventilation and cable pass-through details",
  ),
  rackIntegrationAccessoryConcept: accessoryConcept(
    "rack-integration-accessory-concept",
    "rack-integration",
    "Representative empty graphite rack-integration frame with removable panels and service tray",
  ),
  powerAccessoryConcept: accessoryConcept(
    "power-accessory-concept",
    "power",
    "Representative furniture-integrated power-module housings with blank faceplates",
  ),
  connectivityAccessoryConcept: accessoryConcept(
    "connectivity-accessory-concept",
    "connectivity",
    "Representative furniture-integrated connectivity housings with interchangeable blank faceplates",
  ),
  cableManagementAccessoryConcept: accessoryConcept(
    "cable-management-accessory-concept",
    "cable-management",
    "Representative graphite cable-management kit with tray, cable spine, channels and clips",
  ),
  mobilityAccessoryConcept: accessoryConcept(
    "mobility-accessory-concept",
    "mobility",
    "Representative graphite mobility kit with castors, stabilising feet and an oak push handle",
  ),
  securityAccessoryConcept: accessoryConcept(
    "security-accessory-concept",
    "security",
    "Representative graphite physical-security accessory kit with panel latches and retention modules",
  ),
  accessibilityAccessoryConcept: accessoryConcept(
    "accessibility-accessory-concept",
    "accessibility",
    "Representative human-centred furniture accessory concepts with extended handles, shelves and tactile edge details",
  ),
  equipmentCoolingAccessoryConcept: accessoryConcept(
    "equipment-cooling-accessory-concept",
    "equipment-cooling",
    "Representative graphite equipment-cooling accessory set with ventilation, intake and fan-module housings",
  ),
} satisfies Record<string, MediaAsset>;

export const productConceptMediaBySlug: Partial<Record<string, MediaAsset>> = {
  arc: mediaAssets.arcConcept,
  "arc-pro": mediaAssets.arcProConcept,
  lift: mediaAssets.liftAccessConcept,
  "lift-access": mediaAssets.liftAccessConcept,
  "edu-station": mediaAssets.eduStationConcept,
  edu: mediaAssets.eduTeachingDeskConcept,
  learn: mediaAssets.learnCollaborationTableConcept,
  lab: mediaAssets.labTechnologyBenchConcept,
  flex: mediaAssets.flexMobileConcept,
  "flex-mobile": mediaAssets.flexMobileConcept,
  move: mediaAssets.moveCartConcept,
  "move-pro": mediaAssets.moveProCartConcept,
  "move-duo": mediaAssets.moveDuoCartConcept,
  "move-edu": mediaAssets.moveEduCartConcept,
  "move-xl": mediaAssets.moveXlCartConcept,
  nexus: mediaAssets.nexusCredenzaConcept,
  "nexus-compact": mediaAssets.nexusCompactCredenzaConcept,
  "nexus-rack": mediaAssets.nexusRackCredenzaConcept,
  "nexus-edu": mediaAssets.nexusEduCredenzaConcept,
  "nexus-wall": mediaAssets.nexusWallCredenzaConcept,
  core: mediaAssets.coreEnclosureConcept,
  "core-compact": mediaAssets.coreCompactEnclosureConcept,
  "core-wall": mediaAssets.coreWallEnclosureConcept,
  "core-mobile": mediaAssets.coreMobileEnclosureConcept,
  "core-rack": mediaAssets.coreRackEnclosureConcept,
  panel: mediaAssets.panelControllerStandConcept,
  "panel-desk": mediaAssets.panelDeskControllerConcept,
  "panel-wall": mediaAssets.panelWallControllerConcept,
  schedule: mediaAssets.scheduleRoomPanelConcept,
  dock: mediaAssets.dockTabletConcept,
  mediawall: mediaAssets.mediawallConcept,
  "mediawall-mobile": mediaAssets.mediawallMobileConcept,
  boundary: mediaAssets.boundaryDividerConcept,
  shift: mediaAssets.shiftPartitionConcept,
  focus: mediaAssets.focusCollaborationWallConcept,
  vista: mediaAssets.vistaDisplayStandConcept,
  "vista-duo": mediaAssets.vistaDuoDisplayStandConcept,
  "vista-xl": mediaAssets.vistaXlDisplayStandConcept,
  frame: mediaAssets.frameDisplayStructureConcept,
  "frame-wall": mediaAssets.frameWallDisplayStructureConcept,
  forum: mediaAssets.forumTableConcept,
  converge: mediaAssets.convergeTableConcept,
  huddle: mediaAssets.huddleTableConcept,
  link: mediaAssets.linkModularTableConcept,
  "link-modular": mediaAssets.linkModularTableConcept,
  touch: mediaAssets.touchKioskConcept,
  "touch-wall": mediaAssets.touchWallKioskConcept,
  "touch-mini": mediaAssets.touchMiniKioskConcept,
  way: mediaAssets.wayKioskConcept,
  check: mediaAssets.checkKioskConcept,
  analyst: mediaAssets.analystWorkstationConcept,
};

export const accessoryConceptMediaBySlug: Partial<Record<string, MediaAsset>> =
  {
    "display-mounting": mediaAssets.displayMountingAccessoryConcept,
    "camera-mounting": mediaAssets.cameraMountingAccessoryConcept,
    "soundbar-mounting": mediaAssets.soundbarMountingAccessoryConcept,
    "device-shelves": mediaAssets.deviceShelvesAccessoryConcept,
    "rack-integration": mediaAssets.rackIntegrationAccessoryConcept,
    power: mediaAssets.powerAccessoryConcept,
    connectivity: mediaAssets.connectivityAccessoryConcept,
    "cable-management": mediaAssets.cableManagementAccessoryConcept,
    mobility: mediaAssets.mobilityAccessoryConcept,
    security: mediaAssets.securityAccessoryConcept,
    accessibility: mediaAssets.accessibilityAccessoryConcept,
    "equipment-cooling": mediaAssets.equipmentCoolingAccessoryConcept,
  };

export function findMediaAsset(src: string) {
  return (Object.values(mediaAssets) as MediaAsset[]).find(
    (asset) => asset.src === src || asset.mobileSrc === src,
  );
}
